# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(350, 450)
        main_window.setMinimumSize(QtCore.QSize(350, 450))
        main_window.setMaximumSize(QtCore.QSize(350, 450))
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_g1 = QtWidgets.QPushButton(self.frame)
        self.btn_g1.setMinimumSize(QtCore.QSize(175, 50))
        self.btn_g1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_g1.setObjectName("btn_g1")
        self.verticalLayout_4.addWidget(self.btn_g1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btn_g2 = QtWidgets.QPushButton(self.frame)
        self.btn_g2.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_g2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_g2.setObjectName("btn_g2")
        self.verticalLayout_4.addWidget(self.btn_g2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btn_g3 = QtWidgets.QPushButton(self.frame)
        self.btn_g3.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_g3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_g3.setObjectName("btn_g3")
        self.verticalLayout_4.addWidget(self.btn_g3)
        spacerItem3 = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.btn_g4 = QtWidgets.QPushButton(self.frame)
        self.btn_g4.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_g4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_g4.setObjectName("btn_g4")
        self.verticalLayout_4.addWidget(self.btn_g4)
        spacerItem4 = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.btn_g5 = QtWidgets.QPushButton(self.frame)
        self.btn_g5.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_g5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_g5.setObjectName("btn_g5")
        self.verticalLayout_4.addWidget(self.btn_g5)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.release_notes_btn = QtWidgets.QPushButton(self.centralwidget)
        self.release_notes_btn.setObjectName("release_notes_btn")
        self.horizontalLayout_2.addWidget(self.release_notes_btn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout_2.addWidget(self.btn_quit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Bible Games"))
        self.btn_g1.setText(_translate("main_window", "Name this scripture!"))
        self.btn_g2.setText(_translate("main_window", "Quote that Scripture!"))
        self.btn_g3.setText(_translate("main_window", "Game 3"))
        self.btn_g4.setText(_translate("main_window", "Game 4"))
        self.btn_g5.setText(_translate("main_window", "Game 5"))
        self.release_notes_btn.setText(_translate("main_window", "Release Notes"))
        self.btn_quit.setText(_translate("main_window", "Quit"))

