# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name_scripture.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_name_scripture(object):
    def setupUi(self, name_scripture):
        name_scripture.setObjectName("name_scripture")
        name_scripture.resize(350, 450)
        name_scripture.setMinimumSize(QtCore.QSize(350, 450))
        name_scripture.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        name_scripture.setFont(font)
        name_scripture.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/scroll.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        name_scripture.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(name_scripture)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(name_scripture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restart_btn = QtWidgets.QPushButton(self.frame)
        self.restart_btn.setObjectName("restart_btn")
        self.horizontalLayout_2.addWidget(self.restart_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.passed_lbl = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passed_lbl.setFont(font)
        self.passed_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passed_lbl.setObjectName("passed_lbl")
        self.horizontalLayout_2.addWidget(self.passed_lbl)
        self.good_lcd = QtWidgets.QLCDNumber(self.frame)
        self.good_lcd.setMaximumSize(QtCore.QSize(40, 20))
        self.good_lcd.setStyleSheet("QLCDNumber{\n"
"    color: rgb(0, 160, 0);    \n"
"}")
        self.good_lcd.setSmallDecimalPoint(False)
        self.good_lcd.setDigitCount(3)
        self.good_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.good_lcd.setObjectName("good_lcd")
        self.horizontalLayout_2.addWidget(self.good_lcd)
        self.failed_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.failed_label.setFont(font)
        self.failed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.failed_label.setObjectName("failed_label")
        self.horizontalLayout_2.addWidget(self.failed_label)
        self.bad_lcd = QtWidgets.QLCDNumber(self.frame)
        self.bad_lcd.setMaximumSize(QtCore.QSize(40, 20))
        self.bad_lcd.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 0, 0);    \n"
"}")
        self.bad_lcd.setFrameShape(QtWidgets.QFrame.Box)
        self.bad_lcd.setDigitCount(3)
        self.bad_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bad_lcd.setProperty("value", 0.0)
        self.bad_lcd.setProperty("intValue", 0)
        self.bad_lcd.setObjectName("bad_lcd")
        self.horizontalLayout_2.addWidget(self.bad_lcd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 308, 272))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scripture_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scripture_lbl.sizePolicy().hasHeightForWidth())
        self.scripture_lbl.setSizePolicy(sizePolicy)
        self.scripture_lbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scripture_lbl.setFont(font)
        self.scripture_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scripture_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.scripture_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scripture_lbl.setText("")
        self.scripture_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scripture_lbl.setWordWrap(True)
        self.scripture_lbl.setObjectName("scripture_lbl")
        self.verticalLayout_4.addWidget(self.scripture_lbl)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.choiceA_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceA_btn.sizePolicy().hasHeightForWidth())
        self.choiceA_btn.setSizePolicy(sizePolicy)
        self.choiceA_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceA_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceA_btn.setFont(font)
        self.choiceA_btn.setObjectName("choiceA_btn")
        self.gridLayout.addWidget(self.choiceA_btn, 0, 0, 1, 1)
        self.choiceB_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceB_btn.sizePolicy().hasHeightForWidth())
        self.choiceB_btn.setSizePolicy(sizePolicy)
        self.choiceB_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceB_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceB_btn.setFont(font)
        self.choiceB_btn.setObjectName("choiceB_btn")
        self.gridLayout.addWidget(self.choiceB_btn, 0, 1, 1, 1)
        self.choiceC_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceC_btn.sizePolicy().hasHeightForWidth())
        self.choiceC_btn.setSizePolicy(sizePolicy)
        self.choiceC_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceC_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceC_btn.setFont(font)
        self.choiceC_btn.setObjectName("choiceC_btn")
        self.gridLayout.addWidget(self.choiceC_btn, 1, 0, 1, 1)
        self.choiceD_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceD_btn.sizePolicy().hasHeightForWidth())
        self.choiceD_btn.setSizePolicy(sizePolicy)
        self.choiceD_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceD_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceD_btn.setFont(font)
        self.choiceD_btn.setObjectName("choiceD_btn")
        self.gridLayout.addWidget(self.choiceD_btn, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_btn = QtWidgets.QPushButton(name_scripture)
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.hint_btn = QtWidgets.QPushButton(name_scripture)
        self.hint_btn.setMaximumSize(QtCore.QSize(80, 40))
        self.hint_btn.setObjectName("hint_btn")
        self.horizontalLayout.addWidget(self.hint_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.mainmenu_btn = QtWidgets.QPushButton(name_scripture)
        self.mainmenu_btn.setObjectName("mainmenu_btn")
        self.horizontalLayout.addWidget(self.mainmenu_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(name_scripture)
        QtCore.QMetaObject.connectSlotsByName(name_scripture)

    def retranslateUi(self, name_scripture):
        _translate = QtCore.QCoreApplication.translate
        name_scripture.setWindowTitle(_translate("name_scripture", "Name this scripture!"))
        self.restart_btn.setText(_translate("name_scripture", "Restart"))
        self.passed_lbl.setText(_translate("name_scripture", "Passed:"))
        self.failed_label.setText(_translate("name_scripture", "Failed:"))
        self.choiceA_btn.setText(_translate("name_scripture", "A"))
        self.choiceB_btn.setText(_translate("name_scripture", "B"))
        self.choiceC_btn.setText(_translate("name_scripture", "C"))
        self.choiceD_btn.setText(_translate("name_scripture", "D"))
        self.settings_btn.setText(_translate("name_scripture", "Settings"))
        self.hint_btn.setText(_translate("name_scripture", "Hints: 3"))
        self.mainmenu_btn.setText(_translate("name_scripture", "Main Menu"))


class Ui_quote_scripture(object):
    def setupUi(self, quote_scripture):
        quote_scripture.setObjectName("quote_scripture")
        quote_scripture.resize(350, 450)
        quote_scripture.setMinimumSize(QtCore.QSize(350, 450))
        quote_scripture.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        quote_scripture.setFont(font)
        quote_scripture.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/scroll.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        quote_scripture.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(quote_scripture)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(quote_scripture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restart_btn = QtWidgets.QPushButton(self.frame)
        self.restart_btn.setObjectName("restart_btn")
        self.horizontalLayout_2.addWidget(self.restart_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.passed_lbl = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passed_lbl.setFont(font)
        self.passed_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passed_lbl.setObjectName("passed_lbl")
        self.horizontalLayout_2.addWidget(self.passed_lbl)
        self.good_lcd = QtWidgets.QLCDNumber(self.frame)
        self.good_lcd.setMaximumSize(QtCore.QSize(40, 20))
        self.good_lcd.setStyleSheet("QLCDNumber{\n"
"    color: rgb(0, 160, 0);    \n"
"}")
        self.good_lcd.setSmallDecimalPoint(False)
        self.good_lcd.setDigitCount(3)
        self.good_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.good_lcd.setObjectName("good_lcd")
        self.horizontalLayout_2.addWidget(self.good_lcd)
        self.failed_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.failed_label.setFont(font)
        self.failed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.failed_label.setObjectName("failed_label")
        self.horizontalLayout_2.addWidget(self.failed_label)
        self.bad_lcd = QtWidgets.QLCDNumber(self.frame)
        self.bad_lcd.setMaximumSize(QtCore.QSize(40, 20))
        self.bad_lcd.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 0, 0);    \n"
"}")
        self.bad_lcd.setFrameShape(QtWidgets.QFrame.Box)
        self.bad_lcd.setDigitCount(3)
        self.bad_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bad_lcd.setProperty("value", 0.0)
        self.bad_lcd.setProperty("intValue", 0)
        self.bad_lcd.setObjectName("bad_lcd")
        self.horizontalLayout_2.addWidget(self.bad_lcd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 50))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 308, 48))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scripture_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scripture_lbl.sizePolicy().hasHeightForWidth())
        self.scripture_lbl.setSizePolicy(sizePolicy)
        self.scripture_lbl.setMinimumSize(QtCore.QSize(0, 0))
        self.scripture_lbl.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scripture_lbl.setFont(font)
        self.scripture_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scripture_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.scripture_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scripture_lbl.setText("")
        self.scripture_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scripture_lbl.setWordWrap(True)
        self.scripture_lbl.setObjectName("scripture_lbl")
        self.verticalLayout_4.addWidget(self.scripture_lbl)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textD_lbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textD_lbl.sizePolicy().hasHeightForWidth())
        self.textD_lbl.setSizePolicy(sizePolicy)
        self.textD_lbl.setMinimumSize(QtCore.QSize(151, 105))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textD_lbl.setFont(font)
        self.textD_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textD_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.textD_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textD_lbl.setText("")
        self.textD_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textD_lbl.setWordWrap(True)
        self.textD_lbl.setObjectName("textD_lbl")
        self.gridLayout.addWidget(self.textD_lbl, 4, 1, 1, 1)
        self.choiceA_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceA_btn.sizePolicy().hasHeightForWidth())
        self.choiceA_btn.setSizePolicy(sizePolicy)
        self.choiceA_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceA_btn.setMaximumSize(QtCore.QSize(151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceA_btn.setFont(font)
        self.choiceA_btn.setObjectName("choiceA_btn")
        self.gridLayout.addWidget(self.choiceA_btn, 0, 0, 1, 1)
        self.choiceC_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceC_btn.sizePolicy().hasHeightForWidth())
        self.choiceC_btn.setSizePolicy(sizePolicy)
        self.choiceC_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceC_btn.setMaximumSize(QtCore.QSize(151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceC_btn.setFont(font)
        self.choiceC_btn.setObjectName("choiceC_btn")
        self.gridLayout.addWidget(self.choiceC_btn, 3, 0, 1, 1)
        self.choiceD_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceD_btn.sizePolicy().hasHeightForWidth())
        self.choiceD_btn.setSizePolicy(sizePolicy)
        self.choiceD_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceD_btn.setMaximumSize(QtCore.QSize(151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceD_btn.setFont(font)
        self.choiceD_btn.setObjectName("choiceD_btn")
        self.gridLayout.addWidget(self.choiceD_btn, 3, 1, 1, 1)
        self.choiceB_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choiceB_btn.sizePolicy().hasHeightForWidth())
        self.choiceB_btn.setSizePolicy(sizePolicy)
        self.choiceB_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.choiceB_btn.setMaximumSize(QtCore.QSize(151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.choiceB_btn.setFont(font)
        self.choiceB_btn.setObjectName("choiceB_btn")
        self.gridLayout.addWidget(self.choiceB_btn, 0, 1, 1, 1)
        self.textC_lbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textC_lbl.sizePolicy().hasHeightForWidth())
        self.textC_lbl.setSizePolicy(sizePolicy)
        self.textC_lbl.setMinimumSize(QtCore.QSize(151, 105))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textC_lbl.setFont(font)
        self.textC_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textC_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.textC_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textC_lbl.setText("")
        self.textC_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textC_lbl.setWordWrap(True)
        self.textC_lbl.setObjectName("textC_lbl")
        self.gridLayout.addWidget(self.textC_lbl, 4, 0, 1, 1)
        self.textA_lbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textA_lbl.sizePolicy().hasHeightForWidth())
        self.textA_lbl.setSizePolicy(sizePolicy)
        self.textA_lbl.setMinimumSize(QtCore.QSize(151, 105))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textA_lbl.setFont(font)
        self.textA_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textA_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.textA_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textA_lbl.setText("")
        self.textA_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textA_lbl.setWordWrap(True)
        self.textA_lbl.setObjectName("textA_lbl")
        self.gridLayout.addWidget(self.textA_lbl, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.textB_lbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textB_lbl.sizePolicy().hasHeightForWidth())
        self.textB_lbl.setSizePolicy(sizePolicy)
        self.textB_lbl.setMinimumSize(QtCore.QSize(151, 105))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textB_lbl.setFont(font)
        self.textB_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textB_lbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.textB_lbl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textB_lbl.setText("")
        self.textB_lbl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textB_lbl.setWordWrap(True)
        self.textB_lbl.setObjectName("textB_lbl")
        self.gridLayout.addWidget(self.textB_lbl, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_btn = QtWidgets.QPushButton(quote_scripture)
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.hint_btn = QtWidgets.QPushButton(quote_scripture)
        self.hint_btn.setMaximumSize(QtCore.QSize(80, 40))
        self.hint_btn.setObjectName("hint_btn")
        self.horizontalLayout.addWidget(self.hint_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.mainmenu_btn = QtWidgets.QPushButton(quote_scripture)
        self.mainmenu_btn.setObjectName("mainmenu_btn")
        self.horizontalLayout.addWidget(self.mainmenu_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(quote_scripture)
        QtCore.QMetaObject.connectSlotsByName(quote_scripture)

    def retranslateUi(self, quote_scripture):
        _translate = QtCore.QCoreApplication.translate
        quote_scripture.setWindowTitle(_translate("quote_scripture", "Quote that scripture!"))
        self.restart_btn.setText(_translate("quote_scripture", "Restart"))
        self.passed_lbl.setText(_translate("quote_scripture", "Passed:"))
        self.failed_label.setText(_translate("quote_scripture", "Failed:"))
        self.choiceA_btn.setText(_translate("quote_scripture", "A"))
        self.choiceC_btn.setText(_translate("quote_scripture", "C"))
        self.choiceD_btn.setText(_translate("quote_scripture", "D"))
        self.choiceB_btn.setText(_translate("quote_scripture", "B"))
        self.settings_btn.setText(_translate("quote_scripture", "Settings"))
        self.hint_btn.setText(_translate("quote_scripture", "Hints: 3"))
        self.mainmenu_btn.setText(_translate("quote_scripture", "Main Menu"))


class Ui_scripture_settings(object):
    def setupUi(self, name_scripture_settings):
        name_scripture_settings.setObjectName("name_scripture_settings")
        name_scripture_settings.resize(350, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(name_scripture_settings.sizePolicy().hasHeightForWidth())
        name_scripture_settings.setSizePolicy(sizePolicy)
        name_scripture_settings.setMinimumSize(QtCore.QSize(350, 450))
        name_scripture_settings.setMaximumSize(QtCore.QSize(350, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Leandro Teles/.designer/Images/scroll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        name_scripture_settings.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(name_scripture_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(name_scripture_settings)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.obscure_sbox = QtWidgets.QSpinBox(self.groupBox)
        self.obscure_sbox.setObjectName("obscure_sbox")
        self.gridLayout.addWidget(self.obscure_sbox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.popular_sbox = QtWidgets.QSpinBox(self.groupBox)
        self.popular_sbox.setObjectName("popular_sbox")
        self.gridLayout.addWidget(self.popular_sbox, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.obscure_slider = QtWidgets.QSlider(self.groupBox)
        self.obscure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.obscure_slider.setObjectName("obscure_slider")
        self.gridLayout.addWidget(self.obscure_slider, 1, 1, 1, 1)
        self.popular_slider = QtWidgets.QSlider(self.groupBox)
        self.popular_slider.setOrientation(QtCore.Qt.Horizontal)
        self.popular_slider.setObjectName("popular_slider")
        self.gridLayout.addWidget(self.popular_slider, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.current_setting_lbl = QtWidgets.QLabel(self.groupBox)
        self.current_setting_lbl.setObjectName("current_setting_lbl")
        self.verticalLayout_3.addWidget(self.current_setting_lbl)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(name_scripture_settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.custom_list_chk = QtWidgets.QCheckBox(self.groupBox_2)
        self.custom_list_chk.setChecked(False)
        self.custom_list_chk.setObjectName("custom_list_chk")
        self.verticalLayout_6.addWidget(self.custom_list_chk)
        self.input_file = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_file.setEnabled(False)
        self.input_file.setMinimumSize(QtCore.QSize(150, 0))
        self.input_file.setObjectName("input_file")
        self.verticalLayout_6.addWidget(self.input_file)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browse_file_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_file_btn.setEnabled(False)
        self.browse_file_btn.setObjectName("browse_file_btn")
        self.horizontalLayout.addWidget(self.browse_file_btn)
        self.extract_file_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.extract_file_btn.setEnabled(False)
        self.extract_file_btn.setObjectName("extract_file_btn")
        self.horizontalLayout.addWidget(self.extract_file_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.update_list_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.update_list_btn.setEnabled(False)
        self.update_list_btn.setObjectName("update_list_btn")
        self.verticalLayout_6.addWidget(self.update_list_btn)
        spacerItem = QtWidgets.QSpacerItem(108, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.include_rdo = QtWidgets.QRadioButton(self.groupBox_2)
        self.include_rdo.setEnabled(False)
        self.include_rdo.setChecked(True)
        self.include_rdo.setObjectName("include_rdo")
        self.verticalLayout_6.addWidget(self.include_rdo)
        self.exclude_rdo = QtWidgets.QRadioButton(self.groupBox_2)
        self.exclude_rdo.setEnabled(False)
        self.exclude_rdo.setObjectName("exclude_rdo")
        self.verticalLayout_6.addWidget(self.exclude_rdo)
        self.only_list_rdo = QtWidgets.QRadioButton(self.groupBox_2)
        self.only_list_rdo.setEnabled(False)
        self.only_list_rdo.setObjectName("only_list_rdo")
        self.verticalLayout_6.addWidget(self.only_list_rdo)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.custom_list_box = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.custom_list_box.setEnabled(False)
        self.custom_list_box.setObjectName("custom_list_box")
        self.horizontalLayout_3.addWidget(self.custom_list_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(name_scripture_settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(name_scripture_settings)
        self.obscure_slider.valueChanged['int'].connect(self.obscure_sbox.setValue)
        self.obscure_sbox.valueChanged['int'].connect(self.obscure_slider.setValue)
        self.popular_sbox.valueChanged['int'].connect(self.popular_slider.setValue)
        self.popular_slider.valueChanged['int'].connect(self.popular_sbox.setValue)
        self.input_file.returnPressed.connect(self.browse_file_btn.click)
        self.custom_list_chk.toggled['bool'].connect(self.include_rdo.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.input_file.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.browse_file_btn.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.exclude_rdo.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.only_list_rdo.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.extract_file_btn.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.custom_list_box.setEnabled)
        self.custom_list_chk.toggled['bool'].connect(self.update_list_btn.setEnabled)
        self.include_rdo.clicked.connect(self.update_list_btn.click)
        self.exclude_rdo.clicked.connect(self.update_list_btn.click)
        self.only_list_rdo.clicked.connect(self.update_list_btn.click)
        QtCore.QMetaObject.connectSlotsByName(name_scripture_settings)

    def retranslateUi(self, name_scripture_settings):
        _translate = QtCore.QCoreApplication.translate
        name_scripture_settings.setWindowTitle(_translate("name_scripture_settings", "Settings"))
        self.groupBox.setToolTip(_translate("name_scripture_settings", "<html><head/><body><p>Set obscurity to minimum and popularity to maximum to include ALL scriptures in the testing.</p><p>Raise the obscurity bar to exclude obscure scriptures.</p><p>Lower the popularity bar to exclude popular scriptures.</p></body></html>"))
        self.groupBox.setTitle(_translate("name_scripture_settings", "Difficulty"))
        self.label.setText(_translate("name_scripture_settings", "Popularity -"))
        self.label_3.setText(_translate("name_scripture_settings", "Lower to include more obscure scriptures."))
        self.label_2.setText(_translate("name_scripture_settings", "Obscurity -"))
        self.label_4.setText(_translate("name_scripture_settings", "Higher to include more popular scriptures."))
        self.current_setting_lbl.setText(_translate("name_scripture_settings", "The current setting will present 0 scriptures in the test."))
        self.groupBox_2.setTitle(_translate("name_scripture_settings", "Custom Scripture List"))
        self.label_5.setText(_translate("name_scripture_settings", "Open a file, copy and paste text, or write your own list."))
        self.custom_list_chk.setText(_translate("name_scripture_settings", "Use custom list"))
        self.input_file.setText(_translate("name_scripture_settings", "Browse for a \'.txt\' file to load."))
        self.browse_file_btn.setText(_translate("name_scripture_settings", "Browse"))
        self.extract_file_btn.setText(_translate("name_scripture_settings", "Extract"))
        self.update_list_btn.setText(_translate("name_scripture_settings", "Update List"))
        self.include_rdo.setText(_translate("name_scripture_settings", "Include the list"))
        self.exclude_rdo.setText(_translate("name_scripture_settings", "Exclude the list"))
        self.only_list_rdo.setText(_translate("name_scripture_settings", "Use only the list"))
